### ISSUE TITLE
Scope Studio not compiling or submitting job

### ISSUE THREAD

**Issue by hrnasif** [microsoft/scopestudio-vscode#3]
Type: <b>Bug</b>

I have followed install instructions and tried to submit a script in my repo. The script submits and executes successfully using Visual Studio 2022, but not in VS Code. I am submitting to cosmos15: asimov.partner.ptp.

I see nothing that happens after I right click on my script and try to compile it or submit a job. 

I see a persistant prompt on the bottom bar that says "SCOPE: click to select account". After I click it and select my preferred account, the prompt does not go away.

I have tried signing out and in of my Microsoft account, and I have tried uninstalling and reinstalling Scope Studio. 

Extension version: 0.1.0
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.25393
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper PRO 3945WX 12-Cores      (24 x 3992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.86GB (40.84GB free)|
|Process Argv|--crash-reporter-id e5878a29-eec0-4e01-bb23-931812133a2b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpath:30739704
dh2dc718:30763024
pythonnosm12tcf:30765602

```

</details>

**Comment by yaorobin** [comment]
The root cause should be did not install the dependencies, to trigger the install(if not install automatically), you need open/create a new SCOPE script or try any command of SCOPE below in command pallete.

**Comment by hrnasif** [comment]
I've tried this. I uninstalled SCOPE Studio and deleted the cached directory within .vscode/extensions on my system. I reinstalled SCOPE Studio and did as you suggested, but no dependencies were downloaded.

**Comment by guafan100** [comment]
SCOPE VS Code introduces a new vc format [cluster].[vcname]. And it is incorrectly parsed here...
A workaround is to open .scope/scriptSettings.json and change account from cosmos15.asimov.partner.ptp to vc://cosmos15/asimov.partner.ptp and reload window.

**Comment by guafan100** [comment]
It should be good with v0.1.1-preview now.

**Comment by hrnasif** [comment]
Great, I think this issue is resolved.
