### ISSUE TITLE
Unclear how to add or modify parameters

### ISSUE THREAD

**Issue by andygarcia** [microsoft/scopestudio-vscode#6]
Type: <b>Feature Request</b>

I can change parameters when I submit a job but its not clear where I can do this pre job sumission when I'm developing/compiling iteartively.

Since this is getting pulled from somewhere it would be nice to expose it somewhere - sometimes compilation/code path depends on parameterization (e.g. debug vs prod env).

Extension version: 0.1.1
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by guafan100** [comment]
Thanks for reporting. We have been working on setting parameters and it will be shipped hopefully by the end of this month.

**Comment by Zhanghao-ms** [comment]
@andygarcia we just released a new version v0.2.0, with a parameter set support, could you try to see if it resolves your request?
