### ISSUE TITLE
job submission failure in visual studio code, but success in Visual studio

### ISSUE THREAD

**Issue by helenho-nuup** [microsoft/scopestudio-vscode#7]
Type: <b>Bug</b>

Code submitted to sharedneuadla failed. Identical code submission in Visual Studio succeeded. looks like a reference issue at compilation.

Successful submission to office-adhoc-c14
https://www.cosmos14.osdinfra.net/cosmos/office.adhoc/_Jobs/1bef7a73-e7d5-4ec7-8ae1-3a817cc00732

Error message in visual studio code to sharedneuadla (blueshift) - 
Error 1/1:
**********
E_STORE_USER_FAILURE: Error in getting metadata for path /Microsoft.DataMap.CodeAnnotation.Cosmos.dll.
Operation: GETFILESTATUS failed with   Unknown Error: The remote name could not be resolved: 'sharedneuadla.azuredatalakestore.net' Source: System StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AdlsIndependent.Microsoft.Azure.DataLake.Store.WebTransport.<MakeSingleCallAsync>d__17.MoveNext().
Last encountered exception thrown after 5 tries. [The remote name could not be resolved: 'sharedneuadla.azuredatalakestore.net',The remote name could not be resolved: 'sharedneuadla.azuredatalakestore.net',The remote name could not be resolved: 'sharedneuadla.azuredatalakestore.net',The remote name could not be resolved: 'sharedneuadla.azuredatalakestore.net',The remote name could not be resolved: 'sharedneuadla.azuredatalakestore.net']
[ServerRequestId:]
A user operation has resulted in a store failure.
Please correct the user operation.

at token '@"Microsoft.DataMap.CodeAnnotation.Cosmos.dll"', line 9
near the ###:
**************
ghts reserved.
// </copyright>
//--------------------------------------------------------------------
DEFINE MODULE PrivacyAnnotation 
BEGIN 
 
REFERENCE  ### @"Microsoft.DataMap.CodeAnnotation.Cosmos.dll"; 
REFERENCE @"Microsoft.PrivacyServices.PrivacyAnnotation.dll"; 
 
END MODULE 

code
====
//This is for Germany Quarterly MAU data for CELA

 

// USING Internal.Outlook.Data.Utils;

// USING Internal.Outlook.Data.Utils.Functions;

// USING Internal.Outlook.Data.Utils.Reducers;

 

#DECLARE timeWindow     int    = 1;     // Default Time window (EU -> 1)
#DECLARE includeFabbs   bool   = Convert.ToBoolean("true"); //inlcude Fabbs
#DECLARE dataset        string = "AU";
#DECLARE metricName     string = @dataset;
#SET timeWindow = 92;//92 days in the quarter Jul - Sep 2023
#DECLARE endDateString string = "2023-09-30";
#DECLARE endDate                DateTime = DateTime.Parse(@endDateString);
#DECLARE startDate              DateTime = @endDate.AddDays(-@timeWindow + 1);
#DECLARE startDateString        string   = @startDate.ToString("yyyy-MM-dd");
#DECLARE env string = "eur";
#DECLARE userMetricsView string = "";
#DECLARE outputPath string = "";
#DECLARE gdprModule string = "";

#IF(@env == "nam")
#SET userMetricsView = "/shares/exchange.storage.prod/local/Projects/GXPDataTeam/OlkBuild/Main/Views/OutlookUserMetricsView/OutlookUserMetricsView.view";
#SET outputPath = "/local/Projects/OutlookDataTeam/agupta";
#SET gdprModule = "/shares/exchange.storage.prod/local/Resources/PrivacyAnnotation/PrivacyAnnotation.module";
#ELSEIF(@env == "eur")
#SET userMetricsView = "abfss://filesystem@substrateadlsg2neuprod.dfs.core.windows.net/local/Projects/GXPDataTeam/OlkBuild/Main/Views/OutlookUserMetricsView/OutlookUserMetricsView.view";
#SET outputPath = "abfss://filesystem@sharedneuadlsgen2.dfs.core.windows.net/local/Projects/OutlookDataTeam/agupta";
#SET gdprModule = "abfss://filesystem@substrateadlsg2neuprod.dfs.core.windows.net/local/Resources/PrivacyAnnotation/PrivacyAnnotation.module";
#ENDIF
 
MODULE @gdprModule;
USING Privacy;

// Ouptut Streams.

#DECLARE outputStream   string   = @outputPath + "/MAU_DE_" + @endDate.ToString("yyyy_MM_dd") + ".ss";

users =

    SELECT DISTINCT

           UserId

         , Service

         , CountryCode

   FROM

    (

        VIEW @userMetricsView

        PARAMS

        (

           StartDate    = @startDateString,

           EndDate      = @endDateString,

           DataSet      = @dataset,

           DataScope    = "All",

           CustomParams = "includefabbs=" + @includeFabbs,

           Env = @env 

        )

    );

 

//limit it to OL.COM and O365.COM

 

goodusers =

    SELECT DISTINCT UserId,

                    Service

    FROM users

    WHERE CountryCode == "DE";

 

goodusercount =

    SELECT Service, COUNT(DISTINCT UserId) AS UserCount

    FROM goodusers;

 

[Privacy.Asset.NonPersonal]

OUTPUT goodusercount TO SSTREAM @outputStream WITH STREAMEXPIRY "7";

Extension version: 0.2.1
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (6.93GB free)|
|Process Argv|--crash-reporter-id cba1e4f1-9bfa-4e6a-9b13-709398e2ff18|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2cf:30871583
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc017:30880892
aa_t_chat:30882232

```

</details>

**Comment by guafan100** [comment]
Blueshift hasn't been fully supported in visual studio code.
A workaround to submit blueshift job is to copy the scope.adl command in 'SCOPE' terminal and add -adls [full_stroage_account_path], and run that command in cmd.

**Comment by Zhanghao-ms** [comment]
with -adls option user can do the submission in command line. SCOPE Studio will be supporting this in the coming release.
