### ISSUE TITLE
No SCOPE:Set Parameters found

### ISSUE THREAD

**Issue by Vin-Yuan** [microsoft/scopestudio-vscode#8]
there are no SCOPE:Set Parameters

![image](https://github.com/microsoft/scopestudio-vscode/assets/14286026/46e65381-65f8-43dc-a774-d1d3d8b00e2a)

**Comment by Zhanghao-ms** [comment]
you can right click on SCOPE script editor and find "Set Parameters" in the menu.
![image](https://github.com/microsoft/scopestudio-vscode/assets/125964210/5bcf59b3-7082-4c26-951e-c2e625d30674)
